{
 "title": "K8s Node",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "grafana-kubernetes-datasource" },
   { "name": "ds", "query": "datasource" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": "node" }
  ]
 },
 "panels": [
  { "title": "Filter by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "prometheus-kubernetes-nodeinfo-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum((avg(irate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"system\"}[5m])) * 100))",
     "legendFormat": "system"
    },
    {
     "expr": "sum((avg(irate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"user\"}[5m])) * 100))",
     "legendFormat": "user"
    },
    {
     "expr": "sum((avg(irate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"iowait\"}[5m])) * 100))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum((avg(irate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"steal\"}[5m])) * 100))",
     "legendFormat": "steal"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{kubernetes_node=~\"$node\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{kubernetes_node=~\"$node\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_memory_Active_bytes{kubernetes_node=~\"$node\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Load per Node",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_load1{kubernetes_node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Disk Usage and Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{kubernetes_node=~\"$node\"}) by (kubernetes_node)",
     "legendFormat": "{{ kubernetes_node }} free"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{kubernetes_node=~\"$node\"}) by (kubernetes_node) - sum(node_filesystem_free_bytes) by (kubernetes_node))",
     "legendFormat": "{{ kubernetes_node }} usage"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{kubernetes_node=~\"$node\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{kubernetes_node=~\"$node\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{kubernetes_node=~\"$node\"}[5m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{kubernetes_node=~\"$node\"}[5m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Network Traffic/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{kubernetes_node=~\"$node\"}[5m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{kubernetes_node=~\"$node\"}[5m]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Network Errors/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(node_network_receive_errs_total{kubernetes_node=~\"$node\"})",
     "legendFormat": "in"
    },
    {
     "expr": "sum(node_network_transmit_errs_total{kubernetes_node=~\"$node\"})",
     "legendFormat": "in"
    }
   ]
  },
  {
   "title": "Network Packets/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{kubernetes_node=~\"$node\"}[5m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_packets_total{kubernetes_node=~\"$node\"}[5m]))",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}